"""
Culprit domain models (Pydantic v2).

Defines the canonical data shapes for all Culprit concepts:
Endpoint, AuthContext, RuntimeEvidence, SourceCodebase, Bug,
RootCause, Fix, RegressionTest, Attempt, CulpritReport (§4).

These models are the only permitted way to pass structured data
between layers. Credentials (tokens) are present as Optional fields
but are excluded from serialisation via model_config.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field, field_validator

# ── Enums ────────────────────────────────────────────────────────────────────


class AuthScheme(str, Enum):
    """Authentication scheme supported by the CLI (§2)."""

    BEARER = "BEARER"
    BASIC = "BASIC"
    OAUTH2 = "OAUTH2"
    APIKEY = "APIKEY"
    NONE = "NONE"


class ReportStatus(str, Enum):
    """Final status of a Culprit debug run (§4)."""

    FIXED = "FIXED"
    PARTIAL = "PARTIAL"
    NEEDS_HUMAN = "NEEDS_HUMAN"


# ── §4 Models ────────────────────────────────────────────────────────────────


class Endpoint(BaseModel):
    """A live HTTP endpoint to probe (§4)."""

    url: str
    method: str
    headers: dict[str, str]
    expected_status: int
    actual_status: Optional[int] = None
    body: Optional[str] = None  # request body sent when probing (e.g. JSON)


class AuthContext(BaseModel):
    """
    Holds the resolved authentication state for a run (§4).

    token is excluded from all serialisation to enforce §10.
    """

    scheme: AuthScheme
    token: Optional[str] = Field(default=None, exclude=True)
    expires_at: Optional[datetime] = None


class RuntimeEvidence(BaseModel):
    """Captured HTTP interaction evidence from a live endpoint probe (§4)."""

    endpoint: Endpoint
    request_body: Optional[str] = None
    response_body: str
    response_status: int
    latency_ms: float
    stack_trace_hint: Optional[str] = None


class SourceCodebase(BaseModel):
    """A single local codebase made available to subagents (§4)."""

    name: str
    root_path: Path
    language: str
    entry_points: list[str]


class Bug(BaseModel):
    """The problem statement assembled from CLI inputs (§4)."""

    description: str
    runtime_evidence: list[RuntimeEvidence]
    static_evidence: list[SourceCodebase]


class RootCause(BaseModel):
    """Root cause identified by CauseTracer, with a confidence score (§4)."""

    codebase: str
    file: str
    line: int
    symbol: str
    explanation: str
    confidence: float = Field(ge=0.0, le=1.0)


class FileEdit(BaseModel):
    """One exact search-and-replace edit inside a file (relative to the codebase root)."""

    file: str
    old_text: str  # must occur exactly once in the file
    new_text: str


class Fix(BaseModel):
    """A single candidate patch produced by FixAuthor (§4).

    edits is what gets applied; unified_diff is generated by code from the
    edits (difflib) for display and the report, never parsed back.
    """

    target_codebase: str
    edits: list[FileEdit] = Field(default_factory=list)
    unified_diff: str = ""
    applied_files: list[str] = Field(default_factory=list)


class RegressionTest(BaseModel):
    """A pytest that would have caught this bug, written by Guard (§4)."""

    codebase: str
    file: str
    test_name: str
    code: str


class TestResult(BaseModel):
    """Outcome of running pytest across all codebases (§6, §9)."""

    __test__ = False  # stop pytest from trying to collect this class

    passed: bool
    output: str
    failed_tests: list[str]


class Attempt(BaseModel):
    """Record of one self-healing loop iteration (§4)."""

    num: int
    subagent_outputs: dict[str, object]
    test_result: Optional[TestResult] = None
    failure_reason: Optional[str] = None


# ── §4 Top-level report ──────────────────────────────────────────────────────


class CulpritReport(BaseModel):
    """Final output of a Culprit debug run (§4)."""

    status: ReportStatus
    bug: Bug
    root_cause: Optional[RootCause] = None  # None if the run aborted before tracing
    fix: Optional[Fix] = None
    regression_test: Optional[RegressionTest] = None
    attempts: list[Attempt]
    elapsed_seconds: float
    bobcoins_used: float
    commit_sha: Optional[str] = None  # set when status is FIXED
